# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Vlad Ursache/OneDrive - Technical University of Cluj-Napoca/Desktop/31/SSC/Proiect/ALU_Project/ALU_Project.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Vlad Ursache/OneDrive - Technical University of Cluj-Napoca/Desktop/31/SSC/Proiect/ALU_Project/ALU_Project.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/Vlad Ursache/OneDrive - Technical University of Cluj-Napoca/Desktop/31/SSC/Proiect/ALU_Project/ALU_Project.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Vlad Ursache/OneDrive - Technical University of Cluj-Napoca/Desktop/31/SSC/Proiect/ALU_Project/ALU_Project.srcs/sources_1/new/debounce.vhd}
  {C:/Users/Vlad Ursache/OneDrive - Technical University of Cluj-Napoca/Desktop/31/SSC/Proiect/ALU_Project/ALU_Project.srcs/sources_1/new/CLA_8bit.vhd}
  {C:/Users/Vlad Ursache/OneDrive - Technical University of Cluj-Napoca/Desktop/31/SSC/Proiect/ALU_Project/ALU_Project.srcs/sources_1/new/CLA_32bit.vhd}
  {C:/Users/Vlad Ursache/OneDrive - Technical University of Cluj-Napoca/Desktop/31/SSC/Proiect/ALU_Project/ALU_Project.srcs/sources_1/new/bit_operations.vhd}
  {C:/Users/Vlad Ursache/OneDrive - Technical University of Cluj-Napoca/Desktop/31/SSC/Proiect/ALU_Project/ALU_Project.srcs/sources_1/new/multiplier.vhd}
  {C:/Users/Vlad Ursache/OneDrive - Technical University of Cluj-Napoca/Desktop/31/SSC/Proiect/ALU_Project/ALU_Project.srcs/sources_1/new/divider.vhd}
  {C:/Users/Vlad Ursache/OneDrive - Technical University of Cluj-Napoca/Desktop/31/SSC/Proiect/ALU_Project/ALU_Project.srcs/sources_1/new/displ7seg.vhd}
  {C:/Users/Vlad Ursache/OneDrive - Technical University of Cluj-Napoca/Desktop/31/SSC/Proiect/ALU_Project/ALU_Project.srcs/sources_1/new/ALU.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Vlad Ursache/OneDrive - Technical University of Cluj-Napoca/Desktop/31/SSC/Proiect/ALU_Project/ALU_Project.srcs/constrs_1/new/basys3.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Vlad Ursache/OneDrive - Technical University of Cluj-Napoca/Desktop/31/SSC/Proiect/ALU_Project/ALU_Project.srcs/constrs_1/new/basys3.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Main -part xc7a35tcpg236-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Main_utilization_synth.rpt -pb Main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
